# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 4-18/1 * * 1-5'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DwebhookUrl=${{ secrets.SLACK_WEBHOOK_URL }} -Daccess_key=${{ secrets.AWS_ACCESS_KEY_ID }} -Dsecret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      
